### ISSUE TITLE
Lower SDK bound

### ISSUE THREAD

**Issue by AlexV525** [mrtnetwork/blockchain_utils#1]
Thanks for the great library!

I was wondering whether we could have a lower SDK bound here. Maybe 2.x?

**Comment by AlexV525** [comment]
I can see records are widely used in the package, so it should be at least 3.0. But if we can use tuple to support 2.x then it would be great.

**Comment by mrtnetwork** [comment]
> Thanks for the great library!
> 
> I was wondering whether we could have a lower SDK bound here. Maybe 2.x?

thanks, I will check

**Comment by mrtnetwork** [comment]
> I can see records are widely used in the package, so it should be at least 3.0. But if we can use tuple to support 2.x then it would be great.

I updated the Dart SDK version to 2.17. Additionally, I used inheritance for enums, which takes too much time for versions lower than 2.17, which I can't do now.

**Comment by mrtnetwork** [comment]
> I can see records are widely used in the package, so it should be at least 3.0. But if we can use tuple to support 2.x then it would be great.

I worked on it, I think I can downgrade the SDK version to 2.12, but I am not familiar with Dart versions. Which version do you think is more suitable?

**Comment by AlexV525** [comment]
> Which version do you think is more suitable?

Personally think 2.15 is enough for most of users, which is what we're using for the most popular network request library.

**Comment by mrtnetwork** [comment]
> > Which version do you think is more suitable?
> 
> Personally think 2.15 is enough for most of users, which is what we're using for the most popular network request library.

The new version was published with Dart SDK 2.15
