### ISSUE TITLE
How to generate Solana Public and Private Keys from 12 words Mnemonic

### ISSUE THREAD

**Issue by kishangohel** [mrtnetwork/blockchain_utils#3]
1. Generated mnemonic using `Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);`
2. Generated seed using `final seed = Bip39SeedGenerator(mnemonic).generate();`

Solana Address generated correctly using solana package
`Ed25519HDKeyPair.fromSeedWithHdPath(seed: seed, hdPath: "m/44'/501'/0'/0'").then((value) {
      print(' correct address: ${value.address}');
    });`

How can we get public and private key using this package?

**Comment by mrtnetwork** [comment]
> 1. Generated mnemonic using `Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);`
> 2. Generated seed using `final seed = Bip39SeedGenerator(mnemonic).generate();`
> 
> Solana Address generated correctly using solana package `Ed25519HDKeyPair.fromSeedWithHdPath(seed: seed, hdPath: "m/44'/501'/0'/0'").then((value) { print(' correct address: ${value.address}'); });`
> 
> How can we get public and private key using this package?

Hi
```
// Generate a mnemonic phrase using BIP39 standard with 12 words
final mnemonic = Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);

// Generate a seed from the mnemonic
final seed = Bip39SeedGenerator(mnemonic).generate();

// Create a Solana wallet using BIP44 standard from the generated seed
final solanaWallet = Bip44.fromSeed(seed, Bip44Coins.solana);

// Derive the default HD wallet path for Solana
final solanaDefaultHdWallet = solanaWallet.deriveDefaultPath;

// Extract the private key from the derived wallet
final privateKey = solanaDefaultHdWallet.privateKey;

// Extract the public key from the derived wallet
final publicKey = solanaDefaultHdWallet.publicKey;

// Convert the public key to a Solana address
final address = publicKey.toAddress;

```
The default path in SLIP-0010 Ed25519 key derivation is m/44'/501'/0'. If you want to derive a custom path, you should use the following method:
```
  final customDeriavtion =
      Bip32Slip10Ed25519.fromSeed(seed).derivePath("m/44'/501'/0'/0'");
```

**Comment by kishangohel** [comment]
@mrtnetwork can we do all kind of functionality e.g send/receive solana, send/receive USDC/USDT in solana, listen to transaction upon solana address similar to solana package?

**Comment by kishangohel** [comment]
> > 1. Generated mnemonic using `Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);`
> > 2. Generated seed using `final seed = Bip39SeedGenerator(mnemonic).generate();`
> > 
> > Solana Address generated correctly using solana package `Ed25519HDKeyPair.fromSeedWithHdPath(seed: seed, hdPath: "m/44'/501'/0'/0'").then((value) { print(' correct address: ${value.address}'); });`
> > How can we get public and private key using this package?
> 
> Hi
> 
> ```
> // Generate a mnemonic phrase using BIP39 standard with 12 words
> final mnemonic = Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);
> 
> // Generate a seed from the mnemonic
> final seed = Bip39SeedGenerator(mnemonic).generate();
> 
> // Create a Solana wallet using BIP44 standard from the generated seed
> final solanaWallet = Bip44.fromSeed(seed, Bip44Coins.solana);
> 
> // Derive the default HD wallet path for Solana
> final solanaDefaultHdWallet = solanaWallet.deriveDefaultPath;
> 
> // Extract the private key from the derived wallet
> final privateKey = solanaDefaultHdWallet.privateKey;
> 
> // Extract the public key from the derived wallet
> final publicKey = solanaDefaultHdWallet.publicKey;
> 
> // Convert the public key to a Solana address
> final address = publicKey.toAddress;
> ```
> 
> The default path in SLIP-0010 Ed25519 key derivation is m/44'/501'/0'. If you want to derive a custom path, you should use the following method:
> 
> ```
>   final customDeriavtion =
>       Bip32Slip10Ed25519.fromSeed(seed).derivePath("m/44'/501'/0'/0'");
> ```

@mrtnetwork 
Public address not matching generated with 12 phrase words with Solflare and Phantom

**Comment by mrtnetwork** [comment]
``> > > 1. Generated mnemonic using `Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);`
> > > 2. Generated seed using `final seed = Bip39SeedGenerator(mnemonic).generate();`
> > > 
> > > Solana Address generated correctly using solana package `Ed25519HDKeyPair.fromSeedWithHdPath(seed: seed, hdPath: "m/44'/501'/0'/0'").then((value) { print(' correct address: ${value.address}'); });`
> > > How can we get public and private key using this package?
> > 
> > 
> > Hi
> > ```
> > // Generate a mnemonic phrase using BIP39 standard with 12 words
> > final mnemonic = Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);
> > 
> > // Generate a seed from the mnemonic
> > final seed = Bip39SeedGenerator(mnemonic).generate();
> > 
> > // Create a Solana wallet using BIP44 standard from the generated seed
> > final solanaWallet = Bip44.fromSeed(seed, Bip44Coins.solana);
> > 
> > // Derive the default HD wallet path for Solana
> > final solanaDefaultHdWallet = solanaWallet.deriveDefaultPath;
> > 
> > // Extract the private key from the derived wallet
> > final privateKey = solanaDefaultHdWallet.privateKey;
> > 
> > // Extract the public key from the derived wallet
> > final publicKey = solanaDefaultHdWallet.publicKey;
> > 
> > // Convert the public key to a Solana address
> > final address = publicKey.toAddress;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The default path in SLIP-0010 Ed25519 key derivation is m/44'/501'/0'. If you want to derive a custom path, you should use the following method:
> > ```
> >   final customDeriavtion =
> >       Bip32Slip10Ed25519.fromSeed(seed).derivePath("m/44'/501'/0'/0'");
> > ```
> 
> @mrtnetwork Public address not matching generated with 12 phrase words with Solflare and Phantom


we checked with phantom chrome extension and its ok.

```
  final seed = Bip39SeedGenerator(Mnemonic.fromString(
          "release grab ice belt crack year kiss trash girl work state brisk"))
      .generate();
  final slp = Bip32Slip10Ed25519.fromSeed(seed).derivePath("m/44'/501'/0'/0'");
  final addr = SolAddrEncoder().encodeKey(slp.publicKey.compressed);
  String phantomAddr = "48xZJSzRFnmkmo8MU5CtS36QuVjc2MFiF2MujTiQ1Atv";
  assert(addr == phantomAddr);
```



> @mrtnetwork can we do all kind of functionality e.g send/receive solana, send/receive USDC/USDT in solana, listen to transaction upon solana address similar to solana package?

with this package, u can generate an address and sign Solana transaction but for API and create and serialization transactions you should take a look at some packages in pub.dev (Solana, Solana web3, on_chain, etc)

**Comment by kishangohel** [comment]
> final addr = SolAddrEncoder().encodeKey(slp.publicKey.compressed);

I was checking with below code but using Slip it's correct
**But how to generate private same like phantom**? @mrtnetwork 

```
// Generate a mnemonic phrase using BIP39 standard with 12 words
final mnemonic = Bip39MnemonicGenerator().fromWordsNumber(Bip39WordsNum.wordsNum12);

// Generate a seed from the mnemonic
final seed = Bip39SeedGenerator(mnemonic).generate();

// Create a Solana wallet using BIP44 standard from the generated seed
final solanaWallet = Bip44.fromSeed(seed, Bip44Coins.solana);

// Derive the default HD wallet path for Solana
final solanaDefaultHdWallet = solanaWallet.deriveDefaultPath;

// Extract the private key from the derived wallet
final privateKey = solanaDefaultHdWallet.privateKey;

// Extract the public key from the derived wallet
final publicKey = solanaDefaultHdWallet.publicKey;

// Convert the public key to a Solana address
final address = publicKey.toAddress;
```

**Comment by kishangohel** [comment]
@mrtnetwork can you please help with some of basic functionality using this package
1. Import wallet from private key for solana i.e public address and 12 words mnemonic
2. Generate private key from 12 words mnemonic

**Comment by mrtnetwork** [comment]
> I was checking with below code but using Slip it's correct **But how to generate private same like phantom**? 

Encode, Decode Phantom private key
```
  final seed = Bip39SeedGenerator(Mnemonic.fromString(
          "release grab ice belt crack year kiss trash girl work state brisk"))
      .generate();
  final slp = Bip32Slip10Ed25519.fromSeed(seed).derivePath("m/44'/501'/0'/0'");
  final addr = SolAddrEncoder().encodeKey(slp.publicKey.compressed);
  String phantomAddr = "48xZJSzRFnmkmo8MU5CtS36QuVjc2MFiF2MujTiQ1Atv";
  assert(addr == phantomAddr);
  const phantomPrivateKey =
      "52qt3JzK54cmRupKqdTtc3ECFwbuJgqgXJS7pMhbajBfJ8ZCnXzjpQ8FueJoApgoDTZGLy4nbWg3vksYQH2jfgZk";
  final inBytes = Base58Decoder.decode(phantomPrivateKey);
  assert(
      BytesUtils.bytesEqual(inBytes.sublist(0, Ed25519KeysConst.privKeyByteLen),
          slp.privateKey.raw),
      true);
  assert(
      BytesUtils.bytesEqual(
          inBytes.sublist(Ed25519KeysConst.privKeyByteLen),

          /// remove ed25519 public key prefix
          slp.publicKey.compressed.sublist(1)),
      true);

  final convertToPhantomPrivateKey = Base58Encoder.encode(
      <int>[...slp.privateKey.raw, ...slp.publicKey.compressed.sublist(1)]);
  assert(convertToPhantomPrivateKey == phantomPrivateKey);
```

> @mrtnetwork can you please help with some of basic functionality using this package
> 
> 1. Import wallet from private key for solana i.e public address and 12 words mnemonic
> 2. Generate private key from 12 words mnemonic

this package contains many tools for interacting with blockchain cryptography and related tools.
you can read the readme page and check test files.
I have many plugins and each one only uses this package you should take a look at them
[on_chain](https://github.com/mrtnetwork/On_chain): interacting with Solana, Ethereum, Tron, and Cardano
[bitcoin_base](https://github.com/mrtnetwork/on_chain): interacting with bitcoin and forked networks like bitcoin, dogecoin, bitcoin cash, dash, litecoin, and ...,
[xrpl_dart](https://pub.dev/packages/xrpl_dart): interacting with ripple network
[cosmos_sdk](https://github.com/mrtnetwork/cosmos_sdk/issues): interacting with networks based on cosmos_sdk
[polkadot_dart](https://github.com/mrtnetwork/polkadot_dart): interacting with substrate networks
[ton_dart](https://github.com/mrtnetwork/ton_dart): interacting with Ton network

**Comment by kishangohel** [comment]
Ok will explore on_chain package more
Thanks for help!
