### ISSUE TITLE
Help, BitcoinSigner signMessage not same with bitcoinjs-message

### ISSUE THREAD

**Issue by jankuo** [mrtnetwork/blockchain_utils#5]
I'm sorry, but I need your help, please,  whie `bitcoinjs-message` SignMessage 

```
const ecc = require('tiny-secp256k1');
const { ECPairFactory } = require('ecpair');
const ECPair = ECPairFactory(ecc);
const bitcoinMessage = require('bitcoinjs-message')
var keyPair = ECPair.fromWIF('L19qGaWYzrUhij1Cw6V9GWK4ZiFoeYyTiQJa6e1diAMDTsdKq8CC')
var privateKey = keyPair.privateKey
var message = 'Test123'

var signature = bitcoinMessage.sign(message, privateKey, keyPair.compressed, { segwitType: 'p2wpkh' })
var signature2 = bitcoinMessage.sign(message, privateKey, keyPair.compressed, { segwitType: 'p2sh(p2wpkh)' })
var b64Signature = signature.toString('base64');
var b64Signature2 = signature2.toString('base64');
console.log(b64Signature)
console.log(b64Signature2)


var verified = bitcoinMessage.verify(message, 'L19qGaWYzrUhij1Cw6V9GWK4ZiFoeYyTiQJa6e1diAMDTsdKq8CC', '073MkyUFlcKn/twdmCVlzt8/r7bmMGp7OOBmd9lSnlg692hRlXgySiVWXHy7cdZnbOTvd9E+z2MX4e7ynC5wog==')
console.log(verified ? 'true' : 'false');
```

and run `node main.js`  result is 

```
KNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=
JNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=
/Users/btc/node_modules/bitcoinjs-message/index.js:38
  if (buffer.length !== 65) throw new Error('Invalid signature length')
                            ^

Error: Invalid signature length
    at decodeSignature (/Users/btc/node_modules/bitcoinjs-message/index.js:38:35)
    at Object.verify (/Users/btc/node_modules/bitcoinjs-message/index.js:184:18)
    at Object.<anonymous> (/Users/btc/main.js:17:31)
    at Module._compile (node:internal/modules/cjs/loader:1550:14)
    at Object..js (node:internal/modules/cjs/loader:1702:10)
    at Module.load (node:internal/modules/cjs/loader:1307:32)
    at Function._load (node:internal/modules/cjs/loader:1121:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)

```

and Flutter / Dart code is 

```
BitcoinSigner signer = BitcoinSigner.fromKeyBytes(BytesUtils.fromHexString(
      "755acbf5af9dc2d7f348716848b8205a42e4380c83807695bd3d630a91a52899"));
  final message = utf8.encode("Test123");
  final messagePrefix = '\u0018Bitcoin Signed Message:\n';
  final sign = signer.signMessage(message, messagePrefix);
  print('sign length:' + sign.length.toString());
  print(base64.encode(sign));

  BitcoinVerifier verifier = signer.verifyKey;
  print(verifier.verifyMessage(
      utf8.encode("Test123"),
      messagePrefix,
      base64.decode('JNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=')));
  return;
```

and result is 

```
sign length:64
073MkyUFlcKn/twdmCVlzt8/r7bmMGp7OOBmd9lSnlg692hRlXgySiVWXHy7cdZnbOTvd9E+z2MX4e7ynC5wog==
true
```

`bitcoinjs-message`  's signature passed by blockchain_utils, but bitcoinSigner 's signature  not passed by `bitcoinjs-message`

thank you

**Comment by Miroks123** [comment]
Hello @jankuo  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by mrtnetwork** [comment]
> I'm sorry, but I need your help, please, whie `bitcoinjs-message` SignMessage
> 
> ```
> const ecc = require('tiny-secp256k1');
> const { ECPairFactory } = require('ecpair');
> const ECPair = ECPairFactory(ecc);
> const bitcoinMessage = require('bitcoinjs-message')
> var keyPair = ECPair.fromWIF('L19qGaWYzrUhij1Cw6V9GWK4ZiFoeYyTiQJa6e1diAMDTsdKq8CC')
> var privateKey = keyPair.privateKey
> var message = 'Test123'
> 
> var signature = bitcoinMessage.sign(message, privateKey, keyPair.compressed, { segwitType: 'p2wpkh' })
> var signature2 = bitcoinMessage.sign(message, privateKey, keyPair.compressed, { segwitType: 'p2sh(p2wpkh)' })
> var b64Signature = signature.toString('base64');
> var b64Signature2 = signature2.toString('base64');
> console.log(b64Signature)
> console.log(b64Signature2)
> 
> 
> var verified = bitcoinMessage.verify(message, 'L19qGaWYzrUhij1Cw6V9GWK4ZiFoeYyTiQJa6e1diAMDTsdKq8CC', '073MkyUFlcKn/twdmCVlzt8/r7bmMGp7OOBmd9lSnlg692hRlXgySiVWXHy7cdZnbOTvd9E+z2MX4e7ynC5wog==')
> console.log(verified ? 'true' : 'false');
> ```
> 
> and run `node main.js` result is
> 
> ```
> KNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=
> JNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=
> /Users/btc/node_modules/bitcoinjs-message/index.js:38
>   if (buffer.length !== 65) throw new Error('Invalid signature length')
>                             ^
> 
> Error: Invalid signature length
>     at decodeSignature (/Users/btc/node_modules/bitcoinjs-message/index.js:38:35)
>     at Object.verify (/Users/btc/node_modules/bitcoinjs-message/index.js:184:18)
>     at Object.<anonymous> (/Users/btc/main.js:17:31)
>     at Module._compile (node:internal/modules/cjs/loader:1550:14)
>     at Object..js (node:internal/modules/cjs/loader:1702:10)
>     at Module.load (node:internal/modules/cjs/loader:1307:32)
>     at Function._load (node:internal/modules/cjs/loader:1121:12)
>     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
>     at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
> ```
> 
> and Flutter / Dart code is
> 
> ```
> BitcoinSigner signer = BitcoinSigner.fromKeyBytes(BytesUtils.fromHexString(
>       "755acbf5af9dc2d7f348716848b8205a42e4380c83807695bd3d630a91a52899"));
>   final message = utf8.encode("Test123");
>   final messagePrefix = '\u0018Bitcoin Signed Message:\n';
>   final sign = signer.signMessage(message, messagePrefix);
>   print('sign length:' + sign.length.toString());
>   print(base64.encode(sign));
> 
>   BitcoinVerifier verifier = signer.verifyKey;
>   print(verifier.verifyMessage(
>       utf8.encode("Test123"),
>       messagePrefix,
>       base64.decode('JNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=')));
>   return;
> ```
> 
> and result is
> 
> ```
> sign length:64
> 073MkyUFlcKn/twdmCVlzt8/r7bmMGp7OOBmd9lSnlg692hRlXgySiVWXHy7cdZnbOTvd9E+z2MX4e7ynC5wog==
> true
> ```
> 
> `bitcoinjs-message` 's signature passed by blockchain_utils, but bitcoinSigner 's signature not passed by `bitcoinjs-message`
> 
> thank you

The Bitcoin signer does not include the recovery ID (v) in the signature.
in this case your signature 
```
JNO9zJMlBZXCp/7cHZglZc7fP6+25jBqezjgZnfZUp5YOvdoUZV4MkolVlx8u3HWZ2zk73fRPs9jF+Hu8pwucKI=

```
appears to have an invalid recovery ID of 36. According to [this post](https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v), the valid range for Bitcoin recovery IDs is 27 to 34.
If you want to achieve the same results as bitcoinjs-message, you can modify the process accordingly.
```
  BitcoinSigner signer = BitcoinSigner.fromKeyBytes(BytesUtils.fromHexString(
      "755acbf5af9dc2d7f348716848b8205a42e4380c83807695bd3d630a91a52899"));
  final message = utf8.encode("Test123");
  const messagePrefix = '\u0018Bitcoin Signed Message:\n';
  List<int> sign = signer.signMessage(message, messagePrefix);
  final ecdsaSign = ECDSASignature.fromBytes(sign, Curves.generatorSecp256k1);
  final messgaeHash = QuickCrypto.sha256Hash(
      BitcoinSignerUtils.magicMessage(message, messagePrefix));
  final recover =
      ecdsaSign.recoverPublicKeys(messgaeHash, ETHSignerConst.secp256);
  BitcoinVerifier verifier = signer.verifyKey;
  for (int i = 0; i < recover.length; i++) {
    if (recover[i].point == verifier.verifyKey.publicKey.point) {
      sign = [i + 35, ...sign];
      break;
    }
  }

```

**Comment by jankuo** [comment]
thanks  a lot
