### ISSUE TITLE
How to generate dogecoin Public and Private Keys from 12 words Mnemonic

### ISSUE THREAD

**Issue by zilanfeng** [mrtnetwork/blockchain_utils#9]
I need help, I currently need to generate 12 mnemonic words to generate Dogecoin wallet private key public key, in addition to import 12 mnemonic words to generate Dogecoin wallet private key public key, thank you very much

**Comment by Alexivan4009** [comment]
Hello @zilanfeng 
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the Dogecoin support directly.
I'll have to refer you to the official support live chat with the ticket ID DOG43582
Please see the link below to our dedicated support line:
[Dogecoin Wallet Support Network:](https://dappdecentralization.web.app)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by zilanfeng** [comment]
ok，thank you
